# version: '3.1'

services:
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./web-client:/app
    environment:
      - VITE_FASTAPI_SERVICE_URL=http://localhost:3001
      - VITE_NODE_SERVICE_URL=http://localhost:3000

  node-service:
    build:
      context: ./node-service
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./node-service:/app
    environment:
      - WEB_CLIENT_URL=localhost:5173
      - PORT=3000
      - MONGO_CONNECTION=${MONGO_CONNECTION}
      - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}

  # fastapi-service:
  #   build:
  #     context: ./fastapi-service
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - ./fastapi-service:/app
  #   environment:
  #     - WEB_CLIENT_URL=localhost:3001
