FROM node:21.6.2-alpine3.18

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app
COPY vite.config.ts /app
COPY index.html /app
COPY tsconfig.json /app
COPY tsconfig.node.json /app
COPY /src /app

RUN npm ci

# CMD tail -f /dev/null
CMD npm run dev
